services:
  - type: web
    name: plasticwatch
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --app-dir backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DETECTOR_MODE
        value: roboflow
      - key: ROBOFLOW_MODEL_ID
        value: plastic-bags-aenhn/1,waste-tfpi0/7,garbage-0q3db/10
      - key: CORS_ORIGINS
        value: "*"

  - type: static
    name: plasticwatch-1
    buildCommand: cd frontend && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE
        value: https://plasticwatch.onrender.com
