/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Instantaneous keepalive endpoint that wakes or tests the service without DB overhead.
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Demo Users
         * @description Seeded accounts for the login role picker (SPEC §9). No token required.
         */
        get: operations["list_demo_users_auth_demo_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo Login
         * @description Pick a seeded user by id, or by role; returns a signed demo token.
         */
        post: operations["demo_login_auth_demo_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account with secure password hashing and role support.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email or username and password.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Return the profile of the current authenticated user.
         */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Preview
         * @description Preview likely-plastic detection without saving a report.
         *
         *     Runs the SAME detector as POST /reports, on a temp copy that is deleted before
         *     this returns — so a preview can never disagree with what submitting would say.
         *     Nothing is persisted, so `annotated_jpg_path` is always null here: handing back
         *     a path under a deleted temp dir would only 404.
         */
        post: operations["detect_preview_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Report
         * @description Submit a photo report. Records that waste appears to be present — not who is
         *     responsible (CLAUDE.md §2.3).
         */
        post: operations["create_report_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mine
         * @description The caller's own reports and the status of each one's hotspot.
         */
        get: operations["mine_reports_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description A citizen may read their own reports; an authority may read any. Another
         *     citizen's report is a 404, so report ids can't be probed.
         */
        get: operations["get_report_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotspots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hotspots
         * @description GeoJSON of hotspots, highest Impact first.
         */
        get: operations["list_hotspots_hotspots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotspots/{hotspot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hotspot
         * @description Score breakdown, member reports and the audit trail (the evidence ledger).
         */
        get: operations["get_hotspot_hotspots__hotspot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotspots/{hotspot_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Hotspot
         * @description Human verification gate (CLAUDE.md §2.5). Illegal transition -> 409.
         */
        post: operations["verify_hotspot_hotspots__hotspot_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geo Layers */
        get: operations["geo_layers_geo_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wards
         * @description Ward boundaries with per-ward hotspot stats, for the choropleth.
         */
        get: operations["wards_wards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description All tasks for an authority; only its own for a team.
         */
        get: operations["list_tasks_tasks_get"];
        put?: never;
        /**
         * Create Task
         * @description Optimised route over VERIFIED hotspots. Each hotspot becomes cleanup_scheduled.
         */
        post: operations["create_task_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/stops/{stop_id}/arrive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arrive At Stop
         * @description Mark arrival — recorded only within ARRIVE_RADIUS_M (50 m) of the hotspot.
         */
        post: operations["arrive_at_stop_tasks__task_id__stops__stop_id__arrive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/stops/{stop_id}/after": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload After Photos
         * @description Two after-photos -> before/after record + SUGGESTED verdict (SPEC §14).
         *
         *     Moves the hotspot to cleanup_completed (the team's claim). Never resolves anything:
         *     an authority reviews the photos side by side. Retakes are allowed until reviewed.
         */
        post: operations["upload_after_photos_tasks__task_id__stops__stop_id__after_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/before-after": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Before After */
        get: operations["list_before_after_before_after_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/before-after/{ba_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Before After */
        get: operations["get_before_after_before_after__ba_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/before-after/{ba_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Before After
         * @description Authority inspects before/after side by side and confirms or rejects.
         */
        post: operations["review_before_after_before_after__ba_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public Summary
         * @description Civic totals for the landing page, with NO auth dependency on purpose.
         *
         *     These are the aggregates a public transparency dashboard would publish. The
         *     response is counts only (see PublicSummary); every field that could locate a
         *     hotspot or identify a reporter stays behind `authority_only` on /summary.
         */
        get: operations["public_summary_analytics_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description The 6 KPI cards plus band (open hotspots) and status breakdowns.
         */
        get: operations["summary_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trend
         * @description Reports, hotspots opened and hotspots resolved per UTC day.
         */
        get: operations["trend_analytics_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/wards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ward Stats */
        get: operations["ward_stats_analytics_wards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reset-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Demo
         * @description Wipe and reseed the simulated 45-day demo history (takes ~20 s).
         */
        post: operations["reset_demo_admin_reset_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + PostGIS availability.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AiStatus
         * @description SPEC §6 detector contract.
         * @enum {string}
         */
        AiStatus: "detected" | "not_detected" | "error";
        /** AnalyticsSummary */
        AnalyticsSummary: {
            kpis: components["schemas"]["KpiCards"];
            /** By Band */
            by_band: components["schemas"]["BandCount"][];
            /** By Status */
            by_status: components["schemas"]["StatusCount"][];
            /**
             * Simulated Data
             * @description True while the dashboard is showing seeded demo data (CLAUDE.md §2.2).
             * @default true
             */
            simulated_data: boolean;
            /**
             * Non Attribution Note
             * @default Reports show waste appears to be present; they do not establish who is responsible.
             */
            non_attribution_note: string;
        };
        /** AnalyticsTrend */
        AnalyticsTrend: {
            /** Days */
            days: number;
            /** Points */
            points: components["schemas"]["TrendPoint"][];
            /**
             * Simulated Data
             * @default true
             */
            simulated_data: boolean;
        };
        /** AnalyticsWards */
        AnalyticsWards: {
            /** Wards */
            wards: components["schemas"]["WardStats"][];
            /**
             * Simulated Data
             * @default true
             */
            simulated_data: boolean;
            /**
             * Non Attribution Note
             * @default Reports show waste appears to be present; they do not establish who is responsible.
             */
            non_attribution_note: string;
        };
        /**
         * ArriveRequest
         * @description The team's current position, checked against the stop (SPEC §8: within 50 m).
         */
        ArriveRequest: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Gps Accuracy M */
            gps_accuracy_m?: number | null;
        };
        /**
         * ArriveResponse
         * @description Arrival is checked within 50 m of the stop (SPEC §8).
         */
        ArriveResponse: {
            stop: components["schemas"]["TaskStop"];
            /** Distance M */
            distance_m: number;
            /** Within Range */
            within_range: boolean;
        };
        /** BandCount */
        BandCount: {
            band: components["schemas"]["PriorityBand"];
            /** Count */
            count: number;
        };
        /**
         * BeforeAfterRecord
         * @description SPEC §14. The system computes a verdict but NEVER auto-resolves (CLAUDE.md §2.5).
         *
         *     Absence of detections after cleanup is not proof of cleanliness (CLAUDE.md §2.6).
         */
        BeforeAfterRecord: {
            /** Id */
            id: number;
            /** Task Stop Id */
            task_stop_id?: number | null;
            /** Task Id */
            task_id?: number | null;
            /** Hotspot Id */
            hotspot_id?: number | null;
            hotspot_status?: components["schemas"]["HotspotStatus"] | null;
            /** Before Report Id */
            before_report_id?: string | null;
            /** Before Image Path */
            before_image_path?: string | null;
            /**
             * Before Annotated Path
             * @description Detector-annotated before photo (boxes), if written.
             */
            before_annotated_path?: string | null;
            /**
             * After Image Paths
             * @default []
             */
            after_image_paths: string[];
            /**
             * After Annotated Paths
             * @description Detector-annotated after-photos, in after_image_paths order.
             * @default []
             */
            after_annotated_paths: (string | null)[];
            /** Before Count */
            before_count?: number | null;
            /** Before Area */
            before_area?: number | null;
            /** After Count */
            after_count?: number | null;
            /** After Area */
            after_area?: number | null;
            /**
             * Reduction Ratio
             * @description 1 - (after plastic area / before plastic area), using the worse photo.
             */
            reduction_ratio?: number | null;
            /**
             * Viewpoint Match
             * @description ORB match score against the before image.
             */
            viewpoint_match?: number | null;
            /**
             * Quality Flags
             * @default {}
             */
            quality_flags: {
                [key: string]: unknown;
            };
            verdict?: components["schemas"]["Verdict"] | null;
            /**
             * Verdict Note
             * @description CLAUDE.md §2.5/§2.6.
             * @default A verdict is a suggestion. Only an authority can resolve a hotspot.
             */
            verdict_note: string;
            review_decision?: components["schemas"]["ReviewDecision"] | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Reviewed By Name */
            reviewed_by_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
        };
        /** Body_create_report_reports_post */
        Body_create_report_reports_post: {
            /**
             * Image
             * Format: binary
             */
            image: string;
            /**
             * Lat
             * @description Omit lat/lon to use the photo's EXIF GPS.
             */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** @description browser | exif | pin */
            source?: components["schemas"]["LocationSource"] | null;
            /**
             * Accuracy
             * @description GPS accuracy in metres.
             */
            accuracy?: number | null;
            /** Note */
            note?: string | null;
            /**
             * Reporter Name
             * @description Citizen reporter name.
             */
            reporter_name?: string | null;
            /**
             * Reporter Phone
             * @description Citizen contact phone number.
             */
            reporter_phone?: string | null;
        };
        /** Body_detect_preview_detect_post */
        Body_detect_preview_detect_post: {
            /**
             * Image
             * Format: binary
             * @description Photo to preview. Not saved.
             */
            image: string;
        };
        /** Body_upload_after_photos_tasks__task_id__stops__stop_id__after_post */
        Body_upload_after_photos_tasks__task_id__stops__stop_id__after_post: {
            /**
             * Wide
             * Format: binary
             * @description Wide after-photo.
             */
            wide: string;
            /**
             * Close
             * Format: binary
             * @description Close-up after-photo.
             */
            close: string;
            /**
             * Lat
             * @description GPS at upload; else photo EXIF, else check-in.
             */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
        };
        /**
         * ConfidenceTier
         * @description Raw model confidence is not a calibrated probability (CLAUDE.md §2.7).
         *
         *     A tier is shown beside every number so a score is never read as a promise.
         * @enum {string}
         */
        ConfidenceTier: "low" | "medium" | "high";
        /**
         * DemoLoginRequest
         * @description Pick a seeded user by id, or by role to take the first account with it.
         */
        DemoLoginRequest: {
            /** User Id */
            user_id?: string | null;
            role?: components["schemas"]["UserRole"] | null;
        };
        /**
         * DemoUser
         * @description User account schema (supports both demo and registered users).
         */
        DemoUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            role: components["schemas"]["UserRole"];
            /** Ward Id */
            ward_id?: number | null;
            /**
             * Reliability
             * @description Static 0.5 — learned reporter reliability is out of scope.
             * @default 0.5
             */
            reliability: number;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
        };
        /**
         * DetectPreview
         * @description POST /detect — the frozen DetectorOutput, wrapped with the tier the UI must show.
         *
         *     Composition, not inheritance: `result` is exactly what detector.py returns, so
         *     the §6 contract appears verbatim (as its own schema) in /docs, and the tier is
         *     added at the API layer without touching it (CLAUDE.md §2.7).
         */
        DetectPreview: {
            result: components["schemas"]["DetectorOutput"];
            /** @description Shown beside result.report_confidence; raw confidence is not calibrated. */
            confidence_tier: components["schemas"]["ConfidenceTier"];
            /**
             * Is Simulated
             * @description True while the detector runs in stub mode (fabricated output).
             * @default false
             */
            is_simulated: boolean;
            /**
             * Image Width
             * @description Width the detector measured boxes against.
             */
            image_width: number;
            /**
             * Image Height
             * @description Height the detector measured boxes against.
             */
            image_height: number;
        };
        /**
         * Detection
         * @description One detected litter item. Box coordinates are pixels in the source image.
         */
        Detection: {
            class_name: components["schemas"]["DetectionClass"];
            /**
             * Confidence
             * @description Raw model confidence, not calibrated.
             */
            confidence: number;
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
            /** X2 */
            x2: number;
            /** Y2 */
            y2: number;
            /**
             * Area Frac
             * @description Box area / image area.
             */
            area_frac: number;
        };
        /**
         * DetectionClass
         * @description SPEC §6 — 5 classes collapsed from TACO's 60.
         *
         *     The four plastic_* classes are "plastic-likely". No person, vehicle or
         *     licence-plate class may ever be added here (CLAUDE.md §2.4).
         * @enum {string}
         */
        DetectionClass: "plastic_bottle" | "plastic_bag_film" | "plastic_packaging" | "plastic_other" | "non_plastic_litter";
        /**
         * DetectorOutput
         * @description FROZEN CONTRACT (SPEC §6) — detector.py returns exactly this shape in both
         *     stub and real mode. Do not add, rename or reorder fields without a stage.
         */
        DetectorOutput: {
            /**
             * Plastic Count
             * @description Count of likely-plastic items.
             */
            plastic_count: number;
            /**
             * Plastic Area Frac
             * @description Sum of likely-plastic box areas / image area, capped at 1.0.
             */
            plastic_area_frac: number;
            /**
             * Report Confidence
             * @description Mean of the top-3 plastic-likely confidences.
             */
            report_confidence: number;
            /** Detections */
            detections: components["schemas"]["Detection"][];
            /**
             * Annotated Jpg Path
             * @description Always present; null when no annotated image was written.
             */
            annotated_jpg_path: string | null;
            ai_status: components["schemas"]["AiStatus"];
        };
        /**
         * EvidenceBand
         * @description SPEC §11 Evidence bands (half-open): <0.4 low, [0.4,0.75) moderate, >=0.75 strong.
         * @enum {string}
         */
        EvidenceBand: "low" | "moderate" | "strong";
        /**
         * GeoContext
         * @description Distances stored on the hotspot row at create/update (SPEC §10).
         */
        GeoContext: {
            /** D Drain M */
            d_drain_m?: number | null;
            /** D Water M */
            d_water_m?: number | null;
            /** D School M */
            d_school_m?: number | null;
            /** D Hospital M */
            d_hospital_m?: number | null;
            /** D Market M */
            d_market_m?: number | null;
        };
        /** GeoFeature */
        GeoFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Id */
            id: number;
            /**
             * Geometry
             * @description Any GeoJSON geometry: drains are lines, water polygons, amenities points.
             */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["GeoFeatureProperties"];
        };
        /** GeoFeatureCollection */
        GeoFeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["GeoFeature"][];
            /**
             * Attribution
             * @default © OpenStreetMap contributors
             */
            attribution: string;
        };
        /**
         * GeoFeatureKind
         * @description SPEC §7 geo_features.kind.
         * @enum {string}
         */
        GeoFeatureKind: "drain" | "water" | "school" | "hospital" | "market";
        /** GeoFeatureProperties */
        GeoFeatureProperties: {
            /** Id */
            id: number;
            kind: components["schemas"]["GeoFeatureKind"];
            /** Name */
            name?: string | null;
            /**
             * Source
             * @default osm
             * @enum {string}
             */
            source: "osm" | "manual";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HotspotDetail
         * @description GET /hotspots/{id} — score breakdown, reports, events (the evidence ledger).
         */
        HotspotDetail: {
            /** Id */
            id: number;
            status: components["schemas"]["HotspotStatus"];
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Radius M */
            radius_m?: number | null;
            /** Ward Id */
            ward_id?: number | null;
            /** Ward Name */
            ward_name?: string | null;
            /** First Reported At */
            first_reported_at?: string | null;
            /** Last Reported At */
            last_reported_at?: string | null;
            /** Report Count */
            report_count: number;
            /** Unique Reporters */
            unique_reporters: number;
            /** Recurrence Returns */
            recurrence_returns: number;
            geo_context: components["schemas"]["GeoContext"];
            score_breakdown: components["schemas"]["ScoreBreakdown"];
            /** Reports */
            reports: components["schemas"]["ReportSummary"][];
            /** Events */
            events: components["schemas"]["HotspotEvent"][];
            /** @description Latest before/after record for this hotspot (SPEC §14), if any. */
            before_after?: components["schemas"]["BeforeAfterRecord"] | null;
            /**
             * Cleanup Task Id
             * @description Cleanup task this hotspot is on.
             */
            cleanup_task_id?: number | null;
            /**
             * Cleanup Stop Id
             * @description Its stop, for the after-photo upload.
             */
            cleanup_stop_id?: number | null;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
            /**
             * Non Attribution Note
             * @description Persistent note required on authority views.
             * @default Reports show waste appears to be present; they do not establish who is responsible.
             */
            non_attribution_note: string;
        };
        /**
         * HotspotEvent
         * @description Audit log row. actor_id is the human who acted, null for system transitions.
         */
        HotspotEvent: {
            /** Id */
            id: number;
            from_status?: components["schemas"]["HotspotStatus"] | null;
            to_status: components["schemas"]["HotspotStatus"];
            reason?: components["schemas"]["RejectReason"] | null;
            /** Note */
            note?: string | null;
            /** Actor Id */
            actor_id?: string | null;
            /** Actor Name */
            actor_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HotspotFeature */
        HotspotFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Id */
            id: number;
            geometry: components["schemas"]["PointGeometry"];
            properties: components["schemas"]["HotspotProperties"];
        };
        /** HotspotFeatureCollection */
        HotspotFeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["HotspotFeature"][];
        };
        /**
         * HotspotProperties
         * @description FROZEN — the property set every map marker styles itself from.
         *
         *     d_drain_m / d_water_m were added for the PS-08 dashboard, which shows proximity to
         *     drains and water on the marker popup and in the priority list. Additive only: the
         *     frozen properties above keep their names and meaning.
         */
        HotspotProperties: {
            /** Id */
            id: number;
            status: components["schemas"]["HotspotStatus"];
            /** Impact Score */
            impact_score?: number | null;
            priority_band?: components["schemas"]["PriorityBand"] | null;
            /** Evidence Score */
            evidence_score?: number | null;
            evidence_band?: components["schemas"]["EvidenceBand"] | null;
            /** Report Count */
            report_count: number;
            /** Unique Reporters */
            unique_reporters: number;
            /** Recurrence Returns */
            recurrence_returns: number;
            /** Radius M */
            radius_m?: number | null;
            /** Ward Id */
            ward_id?: number | null;
            /** Ward Name */
            ward_name?: string | null;
            /** First Reported At */
            first_reported_at?: string | null;
            /** Last Reported At */
            last_reported_at?: string | null;
            /**
             * D Drain M
             * @description Stored distance to the nearest drain.
             */
            d_drain_m?: number | null;
            /**
             * D Water M
             * @description Stored distance to the nearest water body.
             */
            d_water_m?: number | null;
            /**
             * Is Simulated
             * @description True when any member report has a fabricated geotag (CLAUDE.md §2.2).
             * @default false
             */
            is_simulated: boolean;
        };
        /**
         * HotspotStatus
         * @description SPEC §13. Only an authority reaches verified / false_positive / resolved.
         * @enum {string}
         */
        HotspotStatus: "ai_detected" | "needs_verification" | "verified" | "cleanup_scheduled" | "cleanup_completed" | "resolved" | "false_positive";
        /**
         * HotspotSummary
         * @description The hotspot a report landed on, as returned to the citizen who reported it.
         */
        HotspotSummary: {
            /** Id */
            id: number;
            status: components["schemas"]["HotspotStatus"];
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Radius M */
            radius_m?: number | null;
            /** Report Count */
            report_count: number;
            /** Unique Reporters */
            unique_reporters: number;
            /** Impact Score */
            impact_score?: number | null;
            priority_band?: components["schemas"]["PriorityBand"] | null;
            /** Evidence Score */
            evidence_score?: number | null;
            evidence_band?: components["schemas"]["EvidenceBand"] | null;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
        };
        /**
         * KpiCards
         * @description The 6 KPI cards of SPEC §2 F8.
         */
        KpiCards: {
            /** Total Reports */
            total_reports: number;
            /** Active Hotspots */
            active_hotspots: number;
            /** Awaiting Verification */
            awaiting_verification: number;
            /** Verified Hotspots */
            verified_hotspots: number;
            /** Resolved Hotspots */
            resolved_hotspots: number;
            /** Median Days To Resolve */
            median_days_to_resolve?: number | null;
        };
        /**
         * LocationSource
         * @description SPEC §7 reports.location_source. Capture order: browser GPS -> EXIF -> map pin.
         * @enum {string}
         */
        LocationSource: "browser" | "exif" | "pin";
        /**
         * LoginRequest
         * @description User login request with email or username and password.
         */
        LoginRequest: {
            /**
             * Email
             * @description Email address or username
             */
            email?: string | null;
            /**
             * Username
             * @description Username or email address
             */
            username?: string | null;
            /** Password */
            password: string;
        };
        /** PointGeometry */
        PointGeometry: {
            /**
             * Type
             * @default Point
             * @constant
             */
            type: "Point";
            /**
             * Coordinates
             * @description [lon, lat] — GeoJSON order.
             */
            coordinates: number[];
        };
        /**
         * PriorityBand
         * @description SPEC §11 Impact bands (half-open): >=70 critical, [50,70) high, [30,50) medium, <30 low.
         * @enum {string}
         */
        PriorityBand: "low" | "medium" | "high" | "critical";
        /**
         * PublicSummary
         * @description Aggregate-only counts for the unauthenticated landing page.
         *
         *     Deliberately narrow: totals and nothing else. No coordinates, no ward names, no
         *     hotspot ids, no reporters — nothing that identifies a place or a person, and
         *     nothing that attributes responsibility (CLAUDE.md §2.3). That is what makes it
         *     safe to serve without a session; widening it would not be.
         */
        PublicSummary: {
            /** Active Hotspots */
            active_hotspots: number;
            /** Awaiting Verification */
            awaiting_verification: number;
            /** Resolved Hotspots */
            resolved_hotspots: number;
            /** Total Reports */
            total_reports: number;
            /**
             * Simulated Data
             * @description True while these counts come from seeded demo data (CLAUDE.md §2.2).
             * @default true
             */
            simulated_data: boolean;
        };
        /**
         * RegisterRequest
         * @description User signup request.
         */
        RegisterRequest: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** @default citizen */
            role: components["schemas"]["UserRole"];
            /** Ward Id */
            ward_id?: number | null;
        };
        /**
         * RejectReason
         * @description SPEC §13.
         * @enum {string}
         */
        RejectReason: "not_plastic" | "no_waste_visible" | "wrong_location" | "duplicate" | "already_cleaned" | "other";
        /**
         * ReportCreateResponse
         * @description Result of POST /reports: detect -> dedupe -> context -> score (SPEC §8).
         */
        ReportCreateResponse: {
            report: components["schemas"]["ReportDetail"];
            /** Detections */
            detections: components["schemas"]["Detection"][];
            hotspot?: components["schemas"]["HotspotSummary"] | null;
            /**
             * Merged
             * @description True when the report joined an existing hotspot rather than creating one.
             */
            merged: boolean;
            /** Duplicate Of */
            duplicate_of?: string | null;
            /**
             * Low Accuracy
             * @description Location accuracy was low; the merge radius was widened.
             * @default false
             */
            low_accuracy: boolean;
            /**
             * Message
             * @description Plain-language outcome for the citizen, e.g. no likely plastic found.
             */
            message: string;
        };
        /** ReportDetail */
        ReportDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Captured At */
            captured_at?: string | null;
            /** Image Path */
            image_path: string;
            /** Annotated Jpg Path */
            annotated_jpg_path?: string | null;
            /** Note */
            note?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            location_source: components["schemas"]["LocationSource"];
            /** Gps Accuracy M */
            gps_accuracy_m?: number | null;
            /**
             * Low Accuracy
             * @description GPS accuracy was poor enough to widen the merge radius.
             * @default false
             */
            low_accuracy: boolean;
            ai_status: components["schemas"]["AiStatus"];
            /** Plastic Count */
            plastic_count?: number | null;
            /** Plastic Area Frac */
            plastic_area_frac?: number | null;
            /** Report Confidence */
            report_confidence?: number | null;
            confidence_tier?: components["schemas"]["ConfidenceTier"] | null;
            /** Hotspot Id */
            hotspot_id?: number | null;
            /** @description Pending / work in progress / completed, as shown to the citizen. */
            hotspot_status?: components["schemas"]["HotspotStatus"] | null;
            /**
             * Is Duplicate
             * @description Matched an existing image; attached as evidence but not counted twice.
             * @default false
             */
            is_duplicate: boolean;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
            /**
             * Reporter Name
             * @description Citizen reporter name for proof.
             */
            reporter_name?: string | null;
            /**
             * Reporter Phone
             * @description Citizen contact phone for proof.
             */
            reporter_phone?: string | null;
            /**
             * Detections
             * @default []
             */
            detections: components["schemas"]["Detection"][];
        };
        /**
         * ReportSummary
         * @description A citizen's own report and the status of the hotspot it belongs to.
         */
        ReportSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Captured At */
            captured_at?: string | null;
            /** Image Path */
            image_path: string;
            /** Annotated Jpg Path */
            annotated_jpg_path?: string | null;
            /** Note */
            note?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            location_source: components["schemas"]["LocationSource"];
            /** Gps Accuracy M */
            gps_accuracy_m?: number | null;
            /**
             * Low Accuracy
             * @description GPS accuracy was poor enough to widen the merge radius.
             * @default false
             */
            low_accuracy: boolean;
            ai_status: components["schemas"]["AiStatus"];
            /** Plastic Count */
            plastic_count?: number | null;
            /** Plastic Area Frac */
            plastic_area_frac?: number | null;
            /** Report Confidence */
            report_confidence?: number | null;
            confidence_tier?: components["schemas"]["ConfidenceTier"] | null;
            /** Hotspot Id */
            hotspot_id?: number | null;
            /** @description Pending / work in progress / completed, as shown to the citizen. */
            hotspot_status?: components["schemas"]["HotspotStatus"] | null;
            /**
             * Is Duplicate
             * @description Matched an existing image; attached as evidence but not counted twice.
             * @default false
             */
            is_duplicate: boolean;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
            /**
             * Reporter Name
             * @description Citizen reporter name for proof.
             */
            reporter_name?: string | null;
            /**
             * Reporter Phone
             * @description Citizen contact phone for proof.
             */
            reporter_phone?: string | null;
        };
        /**
         * ResetDemoResponse
         * @description POST /admin/reset-demo — wipes and reseeds the simulated demo state.
         */
        ResetDemoResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Reports */
            reports: number;
            /** Hotspots */
            hotspots: number;
            /** Users */
            users: number;
            /**
             * Is Simulated
             * @default true
             */
            is_simulated: boolean;
            /**
             * Message
             * @default Demo state reseeded. All geotags in this dataset are simulated.
             */
            message: string;
        };
        /**
         * ReviewDecision
         * @description SPEC §8 POST /before-after/{id}/review. Only confirm_resolved closes a hotspot.
         * @enum {string}
         */
        ReviewDecision: "confirm_resolved" | "reject";
        /**
         * ReviewRequest
         * @description A human authority action. Only confirm_resolved closes the hotspot.
         */
        ReviewRequest: {
            decision: components["schemas"]["ReviewDecision"];
            /** Note */
            note?: string | null;
        };
        /** ReviewResponse */
        ReviewResponse: {
            before_after: components["schemas"]["BeforeAfterRecord"];
            /** Hotspot Id */
            hotspot_id: number;
            hotspot_status: components["schemas"]["HotspotStatus"];
            event: components["schemas"]["HotspotEvent"];
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /** Factors */
            factors: components["schemas"]["ScoreFactor"][];
            /** Impact Score */
            impact_score: number;
            priority_band: components["schemas"]["PriorityBand"];
            /** Evidence Score */
            evidence_score: number;
            evidence_band: components["schemas"]["EvidenceBand"];
            /**
             * Evidence Label
             * @description e.g. "human-verified" once an authority has confirmed.
             */
            evidence_label?: string | null;
            /**
             * Weights Note
             * @description CLAUDE.md §2.8.
             * @default Weights are tunable proposals, not published truth.
             */
            weights_note: string;
            /** Scored At */
            scored_at?: string | null;
        };
        /**
         * ScoreFactor
         * @description One row of the explanation card (SPEC §11).
         *
         *     Weights are tunable proposals documented here, not published truth (CLAUDE.md §2.8).
         */
        ScoreFactor: {
            /**
             * Axis
             * @description Impact ranks the hotspot; Evidence governs what may be claimed.
             * @enum {string}
             */
            axis: "impact" | "evidence";
            /** Factor */
            factor: string;
            /**
             * Value
             * @description Normalised 0-1.
             */
            value: number;
            /** Weight */
            weight: number;
            /**
             * Contribution
             * @description Impact axis: points out of 100. Evidence axis: share of 0-1.
             */
            contribution: number;
            /** Explanation */
            explanation?: string | null;
        };
        /** StatusCount */
        StatusCount: {
            status: components["schemas"]["HotspotStatus"];
            /** Count */
            count: number;
        };
        /**
         * TaskCreateRequest
         * @description Tasks accept VERIFIED hotspots only (SPEC §13) — a non-verified id is a 409.
         */
        TaskCreateRequest: {
            /** Hotspot Ids */
            hotspot_ids: number[];
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /**
             * Depot
             * @description [lon, lat] start/end point of the route.
             */
            depot: number[];
        };
        /** TaskDetail */
        TaskDetail: {
            /** Id */
            id: number;
            status: components["schemas"]["TaskStatus"];
            /** Assigned Team */
            assigned_team?: string | null;
            /** Assigned Team Name */
            assigned_team_name?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Stop Count */
            stop_count: number;
            /** Route Distance M */
            route_distance_m?: number | null;
            /** Route Duration S */
            route_duration_s?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
            /** Depot */
            depot?: number[] | null;
            /** Stops */
            stops: components["schemas"]["TaskStop"][];
            /**
             * Route Geojson
             * @description Decoded ORS geometry, or straight lines when the fallback ran.
             */
            route_geojson?: {
                [key: string]: unknown;
            } | null;
            /** Route Source */
            route_source?: ("ors" | "greedy") | null;
        };
        /**
         * TaskStatus
         * @description SPEC §7 cleanup_tasks.status.
         * @enum {string}
         */
        TaskStatus: "planned" | "in_progress" | "done";
        /** TaskStop */
        TaskStop: {
            /** Id */
            id: number;
            /** Seq */
            seq: number;
            /** Hotspot Id */
            hotspot_id: number;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            priority_band?: components["schemas"]["PriorityBand"] | null;
            /** Arrived At */
            arrived_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Before After Id */
            before_after_id?: number | null;
            /** @description Suggested verdict — never a resolution. */
            verdict?: components["schemas"]["Verdict"] | null;
            review_decision?: components["schemas"]["ReviewDecision"] | null;
        };
        /** TaskSummary */
        TaskSummary: {
            /** Id */
            id: number;
            status: components["schemas"]["TaskStatus"];
            /** Assigned Team */
            assigned_team?: string | null;
            /** Assigned Team Name */
            assigned_team_name?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Stop Count */
            stop_count: number;
            /** Route Distance M */
            route_distance_m?: number | null;
            /** Route Duration S */
            route_duration_s?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Token */
            token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            user: components["schemas"]["DemoUser"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** TrendPoint */
        TrendPoint: {
            /**
             * Date
             * @description ISO date, YYYY-MM-DD.
             */
            date: string;
            /** Reports */
            reports: number;
            /** Hotspots Opened */
            hotspots_opened: number;
            /** Hotspots Resolved */
            hotspots_resolved: number;
        };
        /**
         * UserRole
         * @description SPEC §7 users.role.
         * @enum {string}
         */
        UserRole: "citizen" | "authority" | "team";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @description SPEC §14. A verdict is a suggestion — it never resolves anything by itself.
         * @enum {string}
         */
        Verdict: "likely_cleaned" | "partial" | "not_cleaned" | "inconclusive";
        /**
         * VerifyDecision
         * @description SPEC §8 POST /hotspots/{id}/verify.
         * @enum {string}
         */
        VerifyDecision: "verify" | "reject" | "false_positive";
        /**
         * VerifyRequest
         * @description SPEC §8. A human authority action — nothing here happens automatically.
         */
        VerifyRequest: {
            decision: components["schemas"]["VerifyDecision"];
            /** @description Required when decision is reject or false_positive. */
            reason?: components["schemas"]["RejectReason"] | null;
            /** Note */
            note?: string | null;
        };
        /** VerifyResponse */
        VerifyResponse: {
            /** Hotspot Id */
            hotspot_id: number;
            from_status: components["schemas"]["HotspotStatus"];
            to_status: components["schemas"]["HotspotStatus"];
            event: components["schemas"]["HotspotEvent"];
        };
        /** WardFeature */
        WardFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Id */
            id: number;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["WardProperties"];
        };
        /** WardFeatureCollection */
        WardFeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["WardFeature"][];
            /**
             * Attribution
             * @default © OpenStreetMap contributors
             */
            attribution: string;
        };
        /** WardProperties */
        WardProperties: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Hotspot Count
             * @default 0
             */
            hotspot_count: number;
            /**
             * Open Count
             * @default 0
             */
            open_count: number;
            /**
             * Resolved Count
             * @default 0
             */
            resolved_count: number;
            /** Avg Impact */
            avg_impact?: number | null;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
        };
        /** WardStats */
        WardStats: {
            /** Ward Id */
            ward_id: number;
            /** Ward Name */
            ward_name: string;
            /** Hotspot Count */
            hotspot_count: number;
            /** Open Count */
            open_count: number;
            /** Resolved Count */
            resolved_count: number;
            /** Avg Impact */
            avg_impact?: number | null;
            /**
             * Total Reports
             * @default 0
             */
            total_reports: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_demo_users_auth_demo_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoUser"][];
                };
            };
        };
    };
    demo_login_auth_demo_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoUser"];
                };
            };
        };
    };
    detect_preview_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_detect_preview_detect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_report_reports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mine_reports_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"][];
                };
            };
        };
    };
    get_report_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hotspots_hotspots_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["HotspotStatus"] | null;
                band?: components["schemas"]["PriorityBand"] | null;
                /** @description Ward id. */
                ward?: number | null;
                min_evidence?: number | null;
                /** @description Time slider: recompute scores from reports and events up to this time. Read-only — stored rows are never changed. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotspotFeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hotspot_hotspots__hotspot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotspot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotspotDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_hotspot_hotspots__hotspot_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotspot_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geo_layers_geo_layers_get: {
        parameters: {
            query?: {
                /** @description Omit for all kinds. */
                kind?: components["schemas"]["GeoFeatureKind"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoFeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wards_wards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardFeatureCollection"];
                };
            };
        };
    };
    list_tasks_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"][];
                };
            };
        };
    };
    create_task_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arrive_at_stop_tasks__task_id__stops__stop_id__arrive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArriveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArriveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_after_photos_tasks__task_id__stops__stop_id__after_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
                stop_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_after_photos_tasks__task_id__stops__stop_id__after_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeforeAfterRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_before_after_before_after_get: {
        parameters: {
            query?: {
                /** @description Only records awaiting an authority's review. */
                pending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeforeAfterRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_before_after_before_after__ba_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ba_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeforeAfterRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_before_after_before_after__ba_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ba_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_summary_analytics_public_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSummary"];
                };
            };
        };
    };
    summary_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
        };
    };
    trend_analytics_trend_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsTrend"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ward_stats_analytics_wards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsWards"];
                };
            };
        };
    };
    reset_demo_admin_reset_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetDemoResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
